name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ contains(toJSON(github.event.commits.*.message), '[ci release]') }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Git Fetch Unshallow
        run: git fetch --prune --unshallow

      - name: Enviornment variables
        uses: franzdiebold/github-env-vars-action@v2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0-rc1
          stable: false

      - name: Go modules cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}