name: Test

on:
  pull_request:
  push:

jobs:
  test:
    if: ${{ !contains(toJSON(github.event.commits.*.message), '[ci notest]') }}

    runs-on: ubuntu-latest

    env:
      _VERSION_FLAG: go1.18.0-rc1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0-rc1
          stable: false

      - name: Go modules cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ github.repository }}-${{ env._VERSION_FLAG }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ github.repository }}-${{ env._VERSION_FLAG }}


      - name: Run tests
        run: go test ./...