name: Test

on:
  pull_request:
  push:

jobs:
  test:
    if: ${{ !contains(toJSON(github.event.commits.*.message), '[ci notest]') }}
    strategy:
      matrix:
        go-version:
          - 1.16.x
          - 1.17.x
          - 1.18.0-rc1
        platform:
          - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    env:
      _VERSION_FLAG: go${{ matrix.go-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          stable: ${{ !contains(matrix.go-version, 'rc') }}

      - name: Go modules cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ github.repository }}-${{ env._VERSION_FLAG }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ github.repository }}-${{ env._VERSION_FLAG }}


      - name: Run tests
        run: go test ./...